### PR TITLE
restructure stellar code to reduce calls to horizon

### LINKED ISSUE #690: explorer: restructure stellar code a bit to reduce horizon calls
There are 3 places where we (sometimes) do redundant calls to the escrow:

- In the refund method, we get the source account, then the balance. If we invert this, we save a call if the balance is 0, as then we just exit.
- In the payout farmers method, we get the balance as a sanity check and to provide a nice error message. But in the flow this method is only called after a successful deployment, which only happens after the escrow confirms it has enough balance, so this check is obsolete. If it would fail, it would indicate a serious problem elsewhere. And the tx submit would fail, so we still have a (more cryptic) error.
- when getting the balance, due to paging, we keep loading pages until a page is empty. We can save a call by explicitly setting the page size and verifying that the returned page is equal to this size. If it is smaller, it was the last page.

### PR DESCRIPTION
**Pull request by DylanVerstraete**
closes #690 

Increased the transactions per page when we fetch the balance to 200, this will reduce the number of calls to fetch balance on a heavily used escrow address.

### CODE REVIEW

File: tools/explorer/pkg/stellar/stellar.go [hunk 1]
```diff
@@ -292,6 +292,7 @@ func (w *Wallet) GetBalance(address string, id schema.ID, asset Asset) (xdr.Int6
 	txReq := horizonclient.TransactionRequest{
 		ForAccount: address,
 		Cursor:     cursor,
+		Limit:      200,
```
Comment (LeeSmet) [inline tools/explorer/pkg/stellar/stellar.go]: lets make this a constant, because you will also need to change the condition of the for loop below. rather than checking if the txes are empty, you'll need to check if the amount of txes is smaller than the limit

**Review by LeeSmet — CHANGES_REQUESTED** [review]

File: tools/explorer/pkg/stellar/stellar.go [hunk 2]
```diff
@@ -304,7 +307,7 @@ func (w *Wallet) GetBalance(address string, id schema.ID, asset Asset) (xdr.Int6
 	}
 
 	donors := make(map[string]struct{})
-	for len(txes.Embedded.Records) != 0 {
+	for len(txes.Embedded.Records) < stellarPageLimit {
```
Comment (LeeSmet) [inline tools/explorer/pkg/stellar/stellar.go]: Comming to think of it, this check won't work if its put here. In here we need an unconditional for loop (otherwise we won't process txes from the last page if its not completely full), and the check needs to go near the end, just before we load more txes. if the check passes, we break out. Something like that should work I think

**Review by LeeSmet — CHANGES_REQUESTED** [review]

**Review by LeeSmet — APPROVED** [review]
