### PR TITLE
Fix decomission container is netns does not exist

### LINKED ISSUE #1011: Failed to decomission container
On devnet node: BpTAry1Na2s1J8RAHNyDsbvaBSM3FjR4gMXEKga3UPbs 

```
2020-10-26 16:16:14 | [+] provisiond: 2020-10-26T15:16:14Z error failed to decommission reservation 1920-1 error="decommissioning of reservation failed: failed to delete container network namespace: failed to Statfs \"/var/run/netns/1920-1\": no such file or directory"
2020-10-26 16:16:14 | [+] provisiond: 2020-10-26T15:16:14Z error failed to inspect container for decomission error="container \"1920-1\" in namespace \"ns1\": not found" container=1920-1
```

### PR DESCRIPTION
**Pull request by DylanVerstraete**
Seems like an error was returned from the `ns` package that we were not matching.

### CODE REVIEW

File: pkg/network/nr/container.go [hunk 1]
```diff
@@ -177,17 +177,17 @@ func (nr *NetResource) Leave(containerID string) error {
...
 		Msg("delete container network namespace")
 
-	ns, err := namespace.GetByName(containerID)
-	if err != nil && !os.IsNotExist(err) {
-		return err
-	}
-	if os.IsNotExist(err) {
-		// nothing to do, early return
+	namespc, err := namespace.GetByName(containerID)
+	if _, ok := err.(ns.NSPathNotExistErr); ok {
```
Comment (LeeSmet) [inline pkg/network/nr/container.go:181]: The proper way to do this these days is with `errors.As(...)`, since the error itself does not seem to be used anyhow you might even be able to get away with `errors.Is`, though I'm not sure about that

**Review by LeeSmet — CHANGES_REQUESTED** [review]

File: pkg/network/nr/container.go (hunk 1 above)
Comment (DylanVerstraete) [reply pkg/network/nr/container.go:181]: Tried both those options but I did not get that to work..

Comment (LeeSmet) [reply pkg/network/nr/container.go:181]: That's rather strange since the documentations of errors.As here (https://golang.org/pkg/errors/) literally explains that `As` should be preferred over this construct

Comment (DylanVerstraete) [reply pkg/network/nr/container.go:181]: Ah but wait, I used a pointer while it should have been a concrete type.

**Review by LeeSmet — APPROVED** [review]
