### PR TITLE
flistd: validate the integrity of an flist before mounting it

### LINKED ISSUE #983: Ensure flist hash are correct before mounting it or assume they are present
It seems that if an flist is present on the cache but is not correct, `identityd` doesn't check for consistency.

```
[+] identityd: 2020-10-01T12:04:09Z info flist already in cache url=https://hub.grid.tf/tf-zos-bins.dev/containerd.flist
[+] identityd: 2020-10-01T12:04:09Z info starting 0-fs daemon args=[... ,"-meta","/var/cache/modules/identityd/flist/24a8b2b576779f75c0e1bd2a52909ee8... url=https://hub.grid.tf/tf-zos-bins.dev/containerd.flist
[+] identityd: 2020-10-01T12:04:14Z error fail to start 0-fs daemon error="exit status 1" out= storage=zdb://hub.grid.tf:9900 url=https://hub.grid.tf/tf-zos-bins.dev/containerd.flist
```

Hash is invalid (file is empty, for some reason):
```
# md5sum /var/cache/modules/identityd/flist/24a8b2b576779f75c0e1bd2a52909ee8
d41d8cd98f00b204e9800998ecf8427e  /var/cache/modules/identityd/flist/24a8b2b576779f75c0e1bd2a52909ee8
```

There is two improvement we can made:
- [ ] `identityd` should check consistency and redownload file if it's invalid
- [ ] `flistd` should check file consistency before starting `g8ufs` just in order to provide a clear error message of what happen

### PR DESCRIPTION
**Pull request by zaibon**
fixes #983

### CODE REVIEW

File: pkg/flist/flist.go [hunk 1]
```diff
@@ -438,18 +438,29 @@ func (f *flistModule) downloadFlist(url string) (string, error) {
 	hash, err := f.FlistHash(url)
 	if err == nil {
 		flistPath := filepath.Join(f.flist, strings.TrimSpace(string(hash)))
-		_, err = os.Stat(flistPath)
+		f, err := os.Open(flistPath)
 		if err != nil && !os.IsNotExist(err) {
 			return "", err
 		}
+		defer f.Close()
```
Comment (zaibon) [inline pkg/flist/flist.go:445]: I'm not sure about this. Cause it could be that the `f.saveFlist(resp.Body)` is called while the file is still open, and there is a rename call into this function. I'm not sure if this is a problem or not.

**Review by maxux — APPROVED** [review]
Tested, corrupted flist re-downloaded
