### PR TITLE
networkd: monitor default route on ndm npub4 interface

### LINKED ISSUE #27: solution is not reached for hours
The solution is not reached for hours then it comes back.

image

And when I checked the server it is running in this pod from 56 days, also the gateway itself is reached.

image

**Reservations IDs:** 
kubernetes: https://explorer.testnet.grid.tf/explorer/reservations/461814
expose solution: https://explorer.testnet.grid.tf/explorer/reservations/461850

### LINKED ISSUE #927: Containers can't resolve domain names
suddenly deployed containers can't resolve any domain name.
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/477332
image
image

### LINKED ISSUE #1239: when deploying 3bot networking issues happening
```
3) "fatal: unable to access 'https://github.com/threefoldtech/js-sdk.git/': Could not resolve host: github.com\n"
1) "message"
2) "my2-stderr"
3) "error: Could not fetch origin\n"
1) "message"
2) "my2-stdout"
3) "HEAD is now at 90446f0 Merge pull request #1142 from threefoldtech/development_fix_workloads_ui_epoch\n"
1) "message"
2) "my2-stdout"
2) "my2-stdout"
3) "[ConnectionError]\n"
1) "message"
2) "my2-stdout"
3) "HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/protobuf/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb1e8647d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n"
1) "message"
2) "my2-stdout"

```

and more errors like 
```
3) "    self, \"Failed to establish a new connection: %s\" % e\n"
1) "message"
2) "my2-stderr"
3) "    \xe2\x94\x94 <urllib3.connection.HTTPSConnection object at 0x7f822f5eaa90>\n"
1) "message"
2) "my2-stderr"
3) "\n"
1) "message"
2) "my2-stderr"
3) "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f822f5eaa90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n"
1) "message"

3) "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='explorer.grid.tf', port=443): Max retries exceeded with url: /explorer/users?name=ahmedthabet_my2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f822f5eaa90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n"

```

workloads ids 485755, 485757, 485756, 485758 
ip4: 10.100.7.4
ip6: fd48:4673:6750:7::4
node: 72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib
farm: freefarm
pool id: 2956

### PR DESCRIPTION
**Pull request by zaibon**
It seems udhcp is not the most reliable so we monitor the default route
of the npub4 interface manually and give a push to udhcp when needed to
force the renew of the DHCP lease

fixes #927
fixes https://github.com/threefoldtech/js-sdk/issues/1239
fixes https://github.com/threefoldtech/tfgateway/issues/27

### CODE REVIEW

File: pkg/network/ndmz/dhcp_monitor.go [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+		log.Error().Err(err).Msg("fail to start monitoring dhcp-zos zinit service")
+		return err
+	}
+
+	return err
+}
+
+// Stop stops a zinit background process
+func (d *DHCPMon) stopZinit() error {
+	err := d.z.Stop(d.service)
```
Comment (zaibon) [inline pkg/network/ndmz/dhcp_monitor.go]: @muhamadazmy for some reason this line always return an error even though the service is in `Success` start after.
Any idea what could cause this ?

Comment (muhamadazmy) [reply pkg/network/ndmz/dhcp_monitor.go]: not at the top of my head, I will check.

**Review by delandtj — COMMENTED** [review]
the monitor is a good idea, if there is a hiccup in the dhcp server

**Review by delandtj — APPROVED** [review]
aaait
