### PR TITLE
output clearer error message when farm ID is wrong

### LINKED ISSUE #580: unclear error when using wrong farmer id
As I didn't know that I couldn't use a random farmer ID anymore, I've had some troubles starting my Qemu vm. 

This is the current error message: 
`[+] identityd: 2020-03-17T13:29:56Z info start registration of the node version="not booted from flist"
[+] identityd: 2020-03-17T13:29:56Z error  error="wrong response status code received: 500 Internal Server Error"
[+] identityd: 2020-03-17T13:29:56Z warn registration failed error="wrong response status code received: 500 Internal Server Error" sleep=46.982049071s
`
Should we add a better error message telling the farmer_id is not correct?

PS: Thank you very much @muhamadazmy and @LeeSmet for the help!

### PR DESCRIPTION
**Pull request by zaibon**
we handle case when farm ID has a wronf formaat or when the farm ID does
not exists

Here are the new error message outputted by identityd:
```
[+] identityd: 2020-03-24T16:14:28Z fatal failed to create identity manager error="failed to parse node environment: wrong format for farm ID: strconv.ParseUint: parsing \"123,123\": invalid syntax"
```
```
[+] identityd: 2020-03-24T16:11:31Z error  error="farmer with ID 123123123 does not exists"
```

fixes #580

### CODE REVIEW

File: pkg/identity/store.go [hunk 1]
```diff
@@ -62,6 +62,10 @@ func (s *httpIDStore) RegisterNode(node pkg.Identifier, farm pkg.FarmID, version
 	}
 	defer resp.Body.Close()
 
+	if resp.StatusCode == http.StatusNotFound {
```
Comment (muhamadazmy) [inline pkg/identity/store.go]: I think one of the issues is that bcdb returns 500 if farmer id is not found, which is also need to be fixed in the mock to return proper error code

Comment (zaibon) [reply pkg/identity/store.go]: indeed, and this is also part of this PR: https://github.com/threefoldtech/zos/pull/622/files#diff-cd866ca7f60c9a054ceee3a4b934b6b2R38
