### PR TITLE
Fix #232: Ensure storaged does not crash on boot

### LINKED ISSUE #232: storaged : if impossible to mount crashed (ctree failed) btrfs storaged tries indefinitely
If there are problems with the SSD, nothing works, so there is not even a possibility to try to fix the node without going into some form of rescue mode

### PR DESCRIPTION
**Pull request by LeeSmet**
Rather than returning an error while initializing the storage module,
which ultimately crashes the module, maintain separate lists of
(presumably) faulty devices and storagepools. This allows storaged to
finish intializing with all the known working devices and storagpools in
the system. Also expose these lists over the zbus interface, so other
modules have the ability to check if there is faulty hardware and if so,
take action (e.g. notify farmer).

### CODE REVIEW

**Review by muhamadazmy — COMMENTED** [review]
LGTM. But I am wondering about the behavior of storaged when a disk fails during the normal operation. Not during boot.

For example, if you fail to create a subvolume, if u failed to compute the disk usage (the Total method), etc .. should also storaged move the pool to the broken list, should it try again ?

File: pkg/storage/storage.go [hunk 1]
```diff
@@ -120,11 +134,13 @@ func (s *storageModule) initialize(policy pkg.StoragePolicy) error {
...
+			log.Warn().Msgf("Failed to mount volume %v", volume.Name())
+			continue
 		}
 		log.Debug().Msgf("Mounted volume %s", volume.Name())
+		s.volumes = append(s.volumes, volume)
 	}
-	s.volumes = append(s.volumes, existingPools...)
 
 	// list disks
 	log.Info().Msgf("Finding free disks")
```
Comment (zaibon) [inline pkg/storage/storage.go:160]: Can't you also have some error when listing the devices ?

File: pkg/storage/storage.go [hunk 2]
```diff
@@ -88,6 +92,16 @@ func (s *storageModule) Total(kind pkg.DeviceType) (uint64, error) {
 	return total, nil
 }
 
+// BrokenPools lists the broken storage pools that have been detected
+func (s *storageModule) BrokenPools() []pkg.BrokenPool {
+	return s.brokenPools
```
Comment (zaibon) [inline pkg/storage/storage.go:105]: shouldn't these be protected by a mutex  ?

File: pkg/storage/storage.go [hunk 3]
```diff
@@ -88,6 +92,16 @@ func (s *storageModule) Total(kind pkg.DeviceType) (uint64, error) {
...
+}
+
+// BrokenDevices lists the broken devices that have been detected
+func (s *storageModule) BrokenDevices() []pkg.BrokenDevice {
+	return s.brokenDevices
```
Comment (zaibon) [inline pkg/storage/storage.go:112]: shouldn't these be protected by a mutex  ?

**Review by zaibon — CHANGES_REQUESTED** [review]
The total method needs to be updated to not take in account the amount of storage of the broken devices/pools.

**Comment by LeeSmet** [comment]
> But I am wondering about the behavior of storaged when a disk fails during the normal operation

This should probably be investigated further, though it is not an issue related specifically to storaged imo. After all, once a FS is mounted, storaged is no longer in control, and is not notified if a user gets an error or something. Regardless, I feel that a folow up issue should be created for this since error detection and reporting feels somewhat out of the scope of the original issue.

> The total method needs to be updated to not take in account the amount of storage of the broken devices/pools.

The `Total` method iterates over the elements of the `volumes` field in the storageModule. Since the storagepools which are not mounted are not tracked in this list anymore but in a separate list, this works out of the box.

File: pkg/storage/storage.go (hunk 1 above)
Comment (LeeSmet) [reply pkg/storage/storage.go:160]: I am not intimately familiar with the way lsblk returns it outputs, however I think that it either detects the disk, appending it to the returned disks, or does not detect the disk, and ignores it. Errors returned here are execution errors for the lsblk invocation, and should not be related to any malfunctioning disks afaik. Please let me know if I got this wrong

File: pkg/storage/storage.go (hunk 2 above)
Comment (LeeSmet) [reply pkg/storage/storage.go:105]: I don't think so since the storageModule fields are only written during initialization atm, and access only happens through zbus which should be after initialization. But I'll add it since that can't be defered from just the storage code anyway

**Review by zaibon — APPROVED** [review]
