### PR TITLE
Fixes dangling files in provision cache

### LINKED ISSUE #611: provisiond: is emtpy reservation cached file are found provisiond fails to start

### PR DESCRIPTION
**Pull request by DylanVerstraete**

### CODE REVIEW

File: pkg/provision/local_store.go [hunk 1]
```diff
@@ -121,6 +122,14 @@ func (s *FSStore) removeAllButPersistent(rootPath string) error {
 		if r != nil {
 			return r
 		}
+		// if a file with size 0 is present we can assume its empty and remove it
+		if info.Size() == 0 {
+			err := os.Remove(path)
+			if err != nil {
```
Comment (zaibon) [inline pkg/provision/local_store.go]: Seems in both case you do need to return, so you can just do
```go
return os.Remove(path)
```

**Review by zaibon — CHANGES_REQUESTED** [review]

**Review by zaibon — APPROVED** [review]
