### PR TITLE
Public ns resolv

### LINKED ISSUE #1775: IPv6: two default IPv6 routes set inside VM's
During tests of GE farms for IPv6 we noticed the following (using cloud-init VM's: Ubuntu 20.04 & 22.04).

- IPv6 ping works well
- logging in over ssh with the IPv6 did not work.

While tcpdumping we saw the ssh request where coming in to the public interface, but reply's where send via the private interface. For ICMP, those reply packets are routed correctly trough the public interface. Most VM's we deployed work fine, only sometimes we get a VM where this happens.

A VM it seems gets 2 default IPv6 routes, while for IPv4 there is only one.

```
root@getesttt:~# ip -6 r
::1 dev lo proto kernel metric 256 pref medium
301:b240:d666:9adb::/64 dev ens5 proto kernel metric 256 pref medium
200::/7 via 301:b240:d666:9adb::1 dev ens5 proto static metric 1024 pref medium
2a02:16a8:dc:501::/64 dev ens4 proto ra metric 1024 expires 2591906sec pref medium
2a02:16a8:dc:502::/66 dev ens4 proto ra metric 1024 expires 2591906sec pref medium
2a02:16a8:dc:502:4000::/66 dev ens4 proto ra metric 1024 expires 2591906sec pref medium
2a02:16a8:dc:502:8000::/66 dev ens4 proto ra metric 1024 expires 2591906sec pref medium
2a02:16a8:dc:502:c000::/66 dev ens4 proto ra metric 1024 expires 2591906sec pref medium
fd44:7459:5064:2::/64 dev ens3 proto kernel metric 256 pref medium
fe80::/64 dev ens5 proto kernel metric 256 pref medium
fe80::/64 dev ens4 proto kernel metric 256 pref medium
fe80::/64 dev ens3 proto kernel metric 256 pref medium
default proto static metric 1024 pref medium
        nexthop via fd44:7459:5064:2::1 dev ens3 weight 1 
        nexthop via fe80::a2f8:49ff:fef3:2e47 dev ens4 weight 1 

root@getesttt:~# ip r
default via 195.192.213.254 dev ens4 proto static 
10.20.0.0/16 via 10.20.2.1 dev ens3 proto static 
10.20.2.0/24 dev ens3 proto kernel scope link src 10.20.2.2 
100.64.0.0/16 via 10.20.2.1 dev ens3 proto static 
195.192.213.0/24 dev ens4 proto kernel scope link src 195.192.213.2 

root@getesttt:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fe:86:fd:c1:e4:3c brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 10.20.2.2/24 brd 10.20.2.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fd44:7459:5064:2::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::fc86:fdff:fec1:e43c/64 scope link 
       valid_lft forever preferred_lft forever
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether de:95:d3:a9:61:d6 brd ff:ff:ff:ff:ff:ff
    altname enp0s4
    inet 195.192.213.2/24 brd 195.192.213.255 scope global ens4
       valid_lft forever preferred_lft forever
    inet6 2a02:16a8:dc:501:dc95:d3ff:fea9:61d6/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 2591685sec preferred_lft 604485sec
    inet6 fe80::dc95:d3ff:fea9:61d6/64 scope link 
       valid_lft forever preferred_lft forever
4: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 76:d0:c0:28:57:8f brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    inet6 301:b240:d666:9adb:e092:87c6:57a4:4921/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::74d0:c0ff:fe28:578f/64 scope link 
       valid_lft forever preferred_lft forever
```

A VM in this state (user root):
- 195.192.213.2
- 2a02:16a8:dc:501:dc95:d3ff:fea9:61d6

Azmy's and Lee's key are on there, and the ZOS node that run's the vm can be reached with: ssh root@10.7.1.87

### PR DESCRIPTION
**Pull request by muhamadazmy**
- Set separate nameserver when setting up public config
- Also fixes #1775

### CODE REVIEW

**Review by OmarElawady — DISMISSED** [review]

File: pkg/network/public/public.go [hunk 1]
```diff
@@ -513,6 +515,15 @@ func publicConfig(iface *pkg.PublicConfig) (ips []*net.IPNet, routes []*netlink.
 	return ips, routes, nil
 }
 
+func ensurePublicResolve() error {
+	path := filepath.Join("/etc", "netns", PublicNamespace)
+	if err := os.MkdirAll(path, 0755); err != nil {
+		return errors.Wrap(err, "failed to create public netns directory")
+	}
+	path = filepath.Join(path, "resolv.conf")
+	return ioutil.WriteFile(path, []byte(defaultPublicResolveConf), 0544)
```
Comment (LeeSmet) [inline pkg/network/public/public.go]: ioutil package is deprecated since go 1.16 functionality is now available in `io` and `os` packages

**Review by LeeSmet — CHANGES_REQUESTED** [review]
Looks good other than the comment. Perhaps we should also see about detecting ipv6 and adding an ipv6 nameserver in that case?

File: pkg/network/public/public.go (hunk 1 above)
Comment (muhamadazmy) [reply pkg/network/public/public.go]: I think adding the ipv6 nameserver anyway won't hurt even if there is no ipv6

**Review by LeeSmet — APPROVED** [review]
