### PR TITLE
Derive static mac for ndmz and public ns public if

### LINKED ISSUE #316: networkd: DMZ cannot start if farm dhcp doesn't give IPV4 to public interface of DMZ
```
[-] networkd: 10:32AM FTL failed to create DMZ error="public interface in ndmz didn't not received an IP. make sure dhcp is working"
```

### PR DESCRIPTION
**Pull request by LeeSmet**
Derive a static mac address for the public interace in both the ndmz and public namespace (if available), based on the node ID and a static prefix. This ensures these interfaces always have the same MAC.

Fixes #316

### CODE REVIEW

File: pkg/network/ndmz/ndmz.go [hunk 1]
```diff
@@ -104,7 +107,7 @@ func Create() error {
 			return err
 		}
 		if !received {
-			return errors.Errorf("public interface in ndmz didn't not received an IP. make sure dhcp is working")
+			return errors.Errorf("public interface in ndmz didn't received an IP. make sure dhcp is working")
```
Comment (zaibon) [inline pkg/network/ndmz/ndmz.go]: I prefer to not use abbreviation in error message.
```suggestion
			return errors.Errorf("public interface in ndmz did not received an IP. make sure dhcp is working")
```

**Review by zaibon — APPROVED** [review]
LGTM, just one comment regarding an error message. Other then that we're good to merge.
