### PR TITLE
flistd: force stop the 0-fs process even if mountpoint is already dead

### LINKED ISSUE #956: flistd: fail to umount flist
```
[+] provisiond: 2020-09-22T05:36:23Z info check for expired reservation
[+] provisiond: 2020-09-22T05:36:23Z info reservation expired created=2020-08-11T15:02:30Z duration=1h4m25s id=10908-1 type=kubernetes
[+] provisiond: 2020-09-22T05:36:23Z info start decommissioning reservation duration=1h4m25s expired=true id=10908-1 tag= to-delete=false type=kubernetes
[+] networkd: 2020-09-22T05:36:23Z info Removing tap interface network-id=Qh89hEofqsf3J
[+] flistd: 2020-09-22T05:36:23Z info request unmount flist path=/var/cache/modules/flistd/mountpoint/10908-1
[+] flistd: 2020-09-22T05:36:23Z error fail to umount flist error="invalid argument" path=/var/cache/modules/flistd/mountpoint/10908-1
[+] flistd: 2020-09-22T05:36:25Z error 0-fs daemon did not stop properly error="context deadline exceeded" path=/var/cache/modules/flistd/mountpoint/10908-1
[+] provisiond: 2020-09-22T05:36:25Z error failed to decommission reservation 10908-1 error="decommissioning of reservation failed: could not unmount flist: context deadline exceeded"
```

Seems it can happen the mountpoint is dead but the 0-fs process is still running.

### PR DESCRIPTION
**Pull request by zaibon**
fixes #956

### CODE REVIEW

File: pkg/flist/flist.go [hunk 1]
```diff
@@ -576,4 +587,16 @@ func waitMountedLog(timeout time.Duration, logfile string) error {
 	return <-cErr
 }
 
+func forceStop(pid int) error {
+	log.Info().Int("pid", pid).Msg("trying to force stop by killing the process")
+	p, err := os.FindProcess(int(pid))
+	if err != nil {
+		return err
+	}
+	if err := p.Signal(os.Kill); err != nil {
```
Comment (muhamadazmy) [inline pkg/flist/flist.go]: the main 0-fs mount point is a "unionfs" if it some how was mounted without 0-fs detect that, then it's better to first ask it nicely "SIGTERM" before trying to kill it. This way 0-fs can try to unmount the "read-only" fuse layer, before shutting down. it still not dead by then, we can do sigkill.

**Review by LeeSmet — APPROVED** [review]
