### PR TITLE
fix disk shutdown after decomission filesystem

### LINKED ISSUE #930: Disk shutdown after decomission of last volume turns back on after some time
So when we decomission a filesystem and it was the only one remaining on that disk we shutdown the disk. Turns out that after a few minutes this disk got turned on again. This is most likely btrfs doing some IO under the hood.. 

Proposed fix: run periodically check and see which disks are supossed to be OFF and they seem ON, turns these OFF again

### PR DESCRIPTION
**Pull request by DylanVerstraete**

### CODE REVIEW

File: pkg/storage/storage.go [hunk 1]
```diff
@@ -295,6 +296,8 @@ func (s *storageModule) initialize(policy pkg.StoragePolicy) error {
 		log.Error().Err(err).Msg("Error shutting down unused pools")
 	}
 
+	s.verifyShutdown()
```
Comment (muhamadazmy) [inline pkg/storage/storage.go]: this function name is missleading, it sounds like it does a certain function and exits, while in the matter of fact it monitor the disks.

File: pkg/storage/storage.go [hunk 2]
```diff
@@ -668,3 +671,65 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
 
 	return ch
 }
+
+func (s *storageModule) verifyShutdown() {
```
Comment (muhamadazmy) [inline pkg/storage/storage.go]: The entire function needs re factoring to avoid this deep indentation it makes it very hard to read.

File: pkg/storage/storage.go [hunk 3]
```diff
@@ -668,3 +671,65 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
...
+				}
+			case <-quit:
+				ticker.Stop()
+				return
+			}
+		}
+	}()
+}
+
+func checkDiskPowerStatus(path string) (bool, error) {
```
Comment (muhamadazmy) [inline pkg/storage/storage.go:722]: I am not fully sure but I think there is a smarctl utility library in zos already, this might be not true

**Review by muhamadazmy — CHANGES_REQUESTED** [review]

**Review by zaibon — CHANGES_REQUESTED** [review]
I would like we gather a bit more data about how often and maybe why a disk turn on automatically.
My fear is that with this PR, we could potentially having disk being turn on and off every 5 minutes and I don't think this is that good for the lifetime of the disk.

**Comment by DylanVerstraete** [comment]
You can now ssh to a machine and do `wget -O - http://localhost:8081/debug/vars | grep /dev` which will output the number of shutdowns for each disk.

File: pkg/storage/storage.go (hunk 3 above)
Comment (DylanVerstraete) [reply pkg/storage/storage.go:722]: There is but we don't need this logic anywhere else.

File: pkg/storage/storage.go [hunk 4]
```diff
@@ -668,3 +679,71 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
...
+			log.Debug().Msgf("checking device: %s", device.Path)
+			on, err := checkDiskPowerStatus(device.Path)
+			if err != nil {
+				if err, ok := err.(*exec.ExitError); ok {
+					log.Err(err).Msgf("skipping device")
+					// if cmd exits with exit error the device is shutdown
+					continue
+				}
+			}
+
```
Comment (muhamadazmy) [inline pkg/storage/storage.go:706]: you should instead do 
```go
if !on {
  continue
} 
```

File: pkg/storage/storage.go [hunk 5]
```diff
@@ -668,3 +679,71 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
...
+			_, mounted := pool.Mounted()
+			if mounted {
+				continue
+			}
+
+			if on {
```
Comment (muhamadazmy) [inline pkg/storage/storage.go]: Then you don't need to do this check anymore since you won't be here if disk is off

File: pkg/storage/storage.go [hunk 6]
```diff
@@ -668,3 +679,71 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
...
+	}()
+}
+
+// shutdownDisks will check the disks power status.
+// If a disk is on and it is not mounted then it is not supposed to be on, turn it off
+func (s *storageModule) shutdownDisks() {
+	for _, pool := range s.pools {
+		for _, device := range pool.Devices() {
+			log.Debug().Msgf("checking device: %s", device.Path)
+			on, err := checkDiskPowerStatus(device.Path)
```
Comment (muhamadazmy) [inline pkg/storage/storage.go:701]: Why should a caller of this method know how it's implemented (with exec) ? A caller wouldn't know what kind of underlying error is returned. hence this method should check the error and then return defined types here.

File: pkg/storage/storage.go [hunk 7]
```diff
@@ -668,3 +679,71 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
...
+					return
+				}
+			}
+		}
+	}
+}
+
+func checkDiskPowerStatus(path string) (bool, error) {
+	output, err := exec.Command("smartctl", "-i", "-n", "standby", path).Output()
+	if err != nil {
```
Comment (muhamadazmy) [inline pkg/storage/storage.go:724]: you should instead do the check here and just return the proper "bool"/error flag
if the cmd exits with non success error if the device is down, you should do 
```
if (err is exit error) {
   return false, nil
} else {
   return false, err
}
```
for example

File: pkg/storage/storage.go [hunk 8]
```diff
@@ -668,3 +679,71 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
...
+	for _, pool := range s.pools {
+		for _, device := range pool.Devices() {
+			log.Debug().Msgf("checking device: %s", device.Path)
+			on, err := checkDiskPowerStatus(device.Path)
+			if err != nil {
+				if err, ok := err.(*exec.ExitError); ok {
+					log.Err(err).Msgf("skipping device")
+					// if cmd exits with exit error the device is shutdown
+					continue
+				}
```
Comment (muhamadazmy) [inline pkg/storage/storage.go]: you also never return here if you have a different error :/

File: cmds/storaged/main.go [hunk 9]
```diff
@@ -65,6 +66,12 @@ func main() {
 		log.Info().Msg("shutting down")
 	})
 
+	go func() {
+		if err := http.ListenAndServe(":8080", http.DefaultServeMux); err != nil {
```
Comment (muhamadazmy) [inline cmds/storaged/main.go]: What is this?

**Review by muhamadazmy — CHANGES_REQUESTED** [review]

File: cmds/storaged/main.go (hunk 9 above)
Comment (DylanVerstraete) [reply cmds/storaged/main.go]: https://github.com/threefoldtech/zos/pull/931#issuecomment-691037449

Comment (muhamadazmy) [inline cmds/storaged/main.go]: i don't like this port is hard-coded specially a very "common" port like 8080

Comment (DylanVerstraete) [reply cmds/storaged/main.go]: changed it to 8081

File: cmds/storaged/main.go [hunk 10]
```diff
@@ -65,6 +66,12 @@ func main() {
 		log.Info().Msg("shutting down")
 	})
 
+	go func() {
+		if err := http.ListenAndServe(":8081", http.DefaultServeMux); err != nil {
```
Comment (muhamadazmy) [inline cmds/storaged/main.go]: Are you serious ? :'D please make this configurable via the command line, and make the default something with 5 figures. try 28682 (it's my birthday)

File: pkg/storage/storage.go [hunk 11]
```diff
@@ -668,3 +679,70 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
...
+			}
+		}
+	}
+}
+
+func checkDiskPowerStatus(path string) (bool, error) {
+	output, err := exec.Command("smartctl", "-i", "-n", "standby", path).Output()
+	if err != nil {
+		if err, ok := err.(*exec.ExitError); ok {
+			log.Err(err).Msgf("skipping device")
```
Comment (muhamadazmy) [inline pkg/storage/storage.go]: This log doesn't make any sense here

File: pkg/storage/storage.go [hunk 12]
```diff
@@ -668,3 +679,70 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
...
+// shutdownDisks will check the disks power status.
+// If a disk is on and it is not mounted then it is not supposed to be on, turn it off
+func (s *storageModule) shutdownDisks() {
+	for _, pool := range s.pools {
+		for _, device := range pool.Devices() {
+			log.Debug().Msgf("checking device: %s", device.Path)
+			on, err := checkDiskPowerStatus(device.Path)
+			if err != nil {
+				log.Err(err).Msgf("error occurred while checking disk power status")
+				return
```
Comment (muhamadazmy) [inline pkg/storage/storage.go]: You aware once you return here, there is no way this routine will do it's job ever again? (unless you restart storaged) instead please log an error and try the following disk. return will exit the go routine

File: pkg/storage/storage.go [hunk 13]
```diff
@@ -668,3 +679,70 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
...
+			_, mounted := pool.Mounted()
+			if mounted || !on {
+				continue
+			}
+
+			log.Debug().Msgf("shutting down device %s because it is not mounted and the device is on", device.Path)
+			err = pool.Shutdown()
+			if err != nil {
+				log.Err(err).Msgf("failed to shutdown device %s", device.Path)
+				return
```
Comment (muhamadazmy) [inline pkg/storage/storage.go]: Same comment, if i can't handle one disk it doesn't mean i never try again (and what about the other ones i can shutdown?)

File: pkg/storage/storage.go [hunk 14]
```diff
@@ -668,3 +679,70 @@ func (s *storageModule) Monitor(ctx context.Context) <-chan pkg.PoolsStats {
 
 	return ch
 }
+
+func (s *storageModule) periodicallyCheckDiskShutdown() {
+	ticker := time.NewTicker(5 * time.Minute)
+	quit := make(chan struct{})
```
Comment (muhamadazmy) [inline pkg/storage/storage.go]: You aware this channel is never getting any input? the right way to do it is to pass a `Context` object to this function, then the caller can call the cancel method.

Comment (muhamadazmy) [reply pkg/storage/storage.go]: If you don't need a context (or don't want one) you can simply drop the select stmt and instead have a loop like

```go
for {
 <- ticker.C
 s.shutdownDisks()
}
```

File: pkg/storage/storage.go (hunk 11 above)
Comment (DylanVerstraete) [reply pkg/storage/storage.go]: CI fails if you don't use that error.. Also it does not like it if you replace it with _

**Review by zaibon — APPROVED** [review]
